# Generated by Django 3.2.9 on 2023-06-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='mode_of_transport',
            field=models.CharField(blank=True, choices=[('Development', 'Development'), ('Management', 'Management'), ('QA', 'QA')], db_index=True, default='Development', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(blank=True, choices=[('Task Created', 'Task Created'), ('Task Email Sent', 'Task Email Sent'), ('Task Completed', 'Task Completed')], default='Task Created', max_length=200, null=True),
        ),
    ]
