# Generated by Django 3.2.9 on 2023-06-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_comodity_name_roles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
