# Generated by Django 3.2.9 on 2023-06-13 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotation', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_amount', models.IntegerField()),
                ('release_date', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Monthly Salary', 'Monthly Salary')], max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leve_from', models.DateField()),
                ('leve_to', models.DateField()),
                ('total_leave', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobBegin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippers_address', models.CharField(max_length=200)),
                ('consign_address', models.CharField(max_length=200)),
                ('Piece', models.FloatField(max_length=200)),
                ('weight', models.FloatField(help_text='Enter the weight in kg', max_length=200)),
                ('dimension_height', models.FloatField(max_length=200, null=True)),
                ('dimension_weight', models.FloatField(max_length=200, null=True)),
                ('dimension_breadth', models.FloatField(max_length=200, null=True)),
                ('dimension_pieces', models.FloatField(max_length=200, null=True)),
                ('job_number', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('Job Created', 'Job Created'), ('Job Booked', 'Job Booked'), ('Job Booking Email Sent', 'Job Booking Email Sent')], default='Job Created', max_length=200, null=True)),
                ('commodities', models.ManyToManyField(max_length=600, to='quotation.Commodities')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation')),
                ('work_of_scope', models.ManyToManyField(max_length=200, to='quotation.WorkOFScope')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Quotation Sent', 'Quotation Sent'), ('Quotation Received', 'Quotation Received'), ('Quotation Completed', 'Quotation Completed')], max_length=200, null=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_bill_number', models.CharField(max_length=200)),
                ('airport_destination', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('pieces', models.FloatField(null=True)),
                ('weight_of_shipment', models.FloatField(max_length=10)),
                ('carrier', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('jobs', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobbegin')),
            ],
            options={
                'ordering': ('jobs',),
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_percent', models.IntegerField(default=1, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.salary')),
            ],
        ),
    ]
