# Generated by Django 3.2.9 on 2023-06-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='leve_from',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='leve_to',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='leave',
            name='total_leave_remaining',
            field=models.IntegerField(default=14),
        ),
    ]
