# Generated by Django 3.2.9 on 2023-06-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
