# Generated by Django 3.2.9 on 2022-04-27 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalShippingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('declared_value_for_change', models.CharField(blank=True, max_length=200, null=True)),
                ('declared_value_for_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('CHG', models.CharField(choices=[('PPD', 'PPD'), ('COLL', 'COLL')], default='PPD', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name_and_city', models.CharField(blank=True, max_length=200, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('accounting_information', models.CharField(blank=True, max_length=200, null=True)),
                ('agents_aita_code', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=200, null=True)),
                ('booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.bookjob')),
            ],
        ),
    ]
