# Generated by Django 3.2.9 on 2023-06-13 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotation', '0001_initial'),
        ('Jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments_types_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirportDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_airport', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_flight_date', models.DateField(blank=True, null=True)),
                ('amt_of_insurance', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirportOfDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_routing', models.BooleanField(blank=True, default=False, null=True)),
                ('to_airport', models.CharField(blank=True, max_length=100, null=True)),
                ('to_airline', models.CharField(blank=True, max_length=100, null=True)),
                ('to_airline_prefix_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsignAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_names', models.CharField(max_length=200, null=True)),
                ('addresss', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(blank=True, max_length=100, null=True)),
                ('cngs_code', models.CharField(blank=True, max_length=100, null=True)),
                ('wt_val_payment_type', models.CharField(blank=True, choices=[('PPD', 'PPD'), ('COLL', 'COLL')], max_length=100, null=True)),
                ('declared_val_for_carriage', models.CharField(blank=True, max_length=100, null=True)),
                ('declared_val_for_customs', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandlingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handling_info', models.TextField(blank=True, max_length=500, null=True)),
                ('goods_noofpcsrcp', models.FloatField(blank=True, max_length=20, null=True)),
                ('goods_grossweight', models.FloatField(blank=True, max_length=20, null=True)),
                ('goods_weightunit', models.FloatField(blank=True, max_length=20, null=True)),
                ('goods_chargableweight', models.FloatField(blank=True, max_length=100, null=True)),
                ('goods_ratecharge', models.FloatField(blank=True, max_length=100, null=True)),
                ('goods_to', models.CharField(blank=True, max_length=100, null=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quotation.commodities')),
            ],
        ),
        migrations.CreateModel(
            name='IssuingCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_agent_country', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_agent_iata_code', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_agent_account_no', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_natureandquantity', models.FloatField(max_length=20, null=True)),
                ('weightcharge_prepaid', models.CharField(blank=True, max_length=200, null=True)),
                ('weightcharge_collect', models.CharField(blank=True, max_length=200, null=True)),
                ('valuationcharge_prepaid', models.CharField(blank=True, max_length=200, null=True)),
                ('tax_prepaid', models.FloatField(blank=True, max_length=200, null=True)),
                ('tax_collect', models.FloatField(blank=True, max_length=20, null=True)),
                ('charges_other', models.CharField(blank=True, max_length=100, null=True)),
                ('totalotherchargesdueagent_prepaid', models.CharField(blank=True, max_length=200, null=True)),
                ('totalotherchargesdueagent_collect', models.CharField(blank=True, max_length=200, null=True)),
                ('totalotherchargesduecarrier_prepaid', models.CharField(blank=True, max_length=200, null=True)),
                ('totalotherchargesduecarrier_collect', models.CharField(blank=True, max_length=200, null=True)),
                ('total_prepaid', models.FloatField(blank=True, max_length=200, null=True)),
                ('total_collect', models.FloatField(blank=True, max_length=200, null=True)),
                ('currencyconversionrate', models.FloatField(blank=True, max_length=200, null=True)),
                ('ccchargesindestcurrency', models.FloatField(blank=True, max_length=200, null=True)),
                ('executed_on_date', models.DateField(blank=True, null=True)),
                ('signature_issuingcarrieroragent', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionalShippingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('declared_value_for_change', models.CharField(blank=True, max_length=200, null=True)),
                ('declared_value_for_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('CHG', models.CharField(choices=[('PPD', 'PPD'), ('COLL', 'COLL')], default='PPD', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShippersAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_information', models.ManyToManyField(to='documentation.AccountingInformation')),
                ('airport_of_departure', models.ManyToManyField(to='documentation.AirportOfDeparture')),
                ('airport_of_destination', models.ManyToManyField(to='documentation.AirportDestination')),
                ('booked', models.ManyToManyField(to='Jobs.BookJob')),
                ('consign_address', models.ManyToManyField(to='documentation.ConsignAddress')),
                ('currency', models.ManyToManyField(to='documentation.Currency')),
                ('handling_information', models.ManyToManyField(to='documentation.HandlingInformation')),
                ('issued_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('issuing_carrier', models.ManyToManyField(to='documentation.IssuingCarrier')),
                ('nature_of_goods', models.ManyToManyField(to='documentation.NatureOfGoods')),
                ('shippers_address', models.ManyToManyField(to='documentation.ShippersAddress')),
                ('shipping', models.ManyToManyField(to='documentation.OptionalShippingInformation')),
            ],
        ),
    ]
