# Generated by Django 3.2.9 on 2022-04-30 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotation', '0001_initial'),
        ('documentation', '0002_mainpage_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments_types_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirportDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_airport', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_flight_date', models.DateField(blank=True, null=True)),
                ('amt_of_insurance', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirportOfDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_routing', models.CharField(blank=True, max_length=100, null=True)),
                ('to_airport', models.CharField(blank=True, max_length=100, null=True)),
                ('to_airline', models.CharField(blank=True, max_length=100, null=True)),
                ('to_airline_prefix_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsignAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(blank=True, max_length=100, null=True)),
                ('cngs_code', models.CharField(blank=True, max_length=100, null=True)),
                ('wt_val_payment_type', models.CharField(blank=True, choices=[('PPD', 'PPD'), ('COLL', 'COLL')], max_length=100, null=True)),
                ('declared_val_for_carriage', models.CharField(blank=True, max_length=100, null=True)),
                ('declared_val_for_customs', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuingCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_agent_country', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_agent_iata_code', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_agent_account_no', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_natureandquantity', models.FloatField(max_length=20, null=True)),
                ('weightcharge_prepaid', models.CharField(blank=True, max_length=200, null=True)),
                ('weightcharge_collect', models.CharField(blank=True, max_length=200, null=True)),
                ('valuationcharge_prepaid', models.CharField(blank=True, max_length=200, null=True)),
                ('tax_prepaid', models.FloatField(blank=True, max_length=200, null=True)),
                ('tax_collect', models.FloatField(blank=True, max_length=20, null=True)),
                ('charges_other', models.CharField(blank=True, max_length=100, null=True)),
                ('totalotherchargesdueagent_prepaid', models.CharField(blank=True, max_length=200, null=True)),
                ('totalotherchargesdueagent_collect', models.CharField(blank=True, max_length=200, null=True)),
                ('total_prepaid', models.FloatField(blank=True, max_length=200, null=True)),
                ('total_collect', models.FloatField(blank=True, max_length=200, null=True)),
                ('currencyconversionrate', models.FloatField(blank=True, max_length=200, null=True)),
                ('ccchargesindestcurrency', models.FloatField(blank=True, max_length=200, null=True)),
                ('executed_on_date', models.DateField(blank=True, null=True)),
                ('signature_issuingcarrieroragent', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippersAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='agents_aita_code',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='carrier_name_and_city',
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='issued_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HandlingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handling_info', models.TextField(blank=True, max_length=500, null=True)),
                ('goods_noofpcsrcp', models.FloatField(blank=True, max_length=20, null=True)),
                ('goods_grossweight', models.FloatField(blank=True, max_length=20, null=True)),
                ('goods_weightunit', models.FloatField(blank=True, max_length=20, null=True)),
                ('goods_chargableweight', models.FloatField(blank=True, max_length=100, null=True)),
                ('goods_ratecharge', models.FloatField(blank=True, max_length=100, null=True)),
                ('goods_to', models.CharField(blank=True, max_length=100, null=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quotation.commodities')),
            ],
        ),
        migrations.AddField(
            model_name='mainpage',
            name='airport_of_departure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.airportofdeparture'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='airport_of_destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.airportdestination'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='consign_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.consignaddress'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.CharField, to='documentation.currency'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='handling_information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.CharField, to='documentation.handlinginformation'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='issuing_carrier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.issuingcarrier'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='nature_of_goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.CharField, to='documentation.natureofgoods'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='shippers_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.shippersaddress'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='accounting_information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.accountinginformation'),
        ),
    ]
