# Generated by Django 3.2.9 on 2022-05-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20220430_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='natureofgoods',
            name='totalotherchargesduecarrier_collect',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='natureofgoods',
            name='totalotherchargesduecarrier_prepaid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='airportofdeparture',
            name='requested_routing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
