# Generated by Django 3.2.9 on 2022-05-01 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentation', '0004_auto_20220501_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='accounting_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.accountinginformation'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='airport_of_departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.airportofdeparture'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='airport_of_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.airportdestination'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='consign_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.consignaddress'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='documentation.currency'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='handling_information',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='documentation.handlinginformation'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='issuing_carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.issuingcarrier'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='nature_of_goods',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='documentation.natureofgoods'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='shippers_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.shippersaddress'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.optionalshippinginformation'),
        ),
    ]
