# Generated by Django 3.2.9 on 2022-05-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_auto_20220501_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignaddress',
            old_name='address',
            new_name='addresss',
        ),
        migrations.RenameField(
            model_name='consignaddress',
            old_name='company_name',
            new_name='company_names',
        ),
    ]
