# Generated by Django 3.2.9 on 2022-05-10 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentation', '0006_auto_20220505_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='accounting_information',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='accounting_information',
            field=models.ManyToManyField(to='documentation.AccountingInformation'),
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='airport_of_departure',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='airport_of_departure',
            field=models.ManyToManyField(to='documentation.AirportOfDeparture'),
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='airport_of_destination',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='airport_of_destination',
            field=models.ManyToManyField(to='documentation.AirportDestination'),
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='consign_address',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='consign_address',
            field=models.ManyToManyField(to='documentation.ConsignAddress'),
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='currency',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='currency',
            field=models.ManyToManyField(to='documentation.Currency'),
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='handling_information',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='handling_information',
            field=models.ManyToManyField(to='documentation.HandlingInformation'),
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='issued_by',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='issued_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='issuing_carrier',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='issuing_carrier',
            field=models.ManyToManyField(to='documentation.IssuingCarrier'),
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='nature_of_goods',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='nature_of_goods',
            field=models.ManyToManyField(to='documentation.NatureOfGoods'),
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='shippers_address',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='shippers_address',
            field=models.ManyToManyField(to='documentation.ShippersAddress'),
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='shipping',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='shipping',
            field=models.ManyToManyField(to='documentation.OptionalShippingInformation'),
        ),
    ]
