# Generated by Django 3.2.9 on 2022-05-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
        ('documentation', '0007_auto_20220510_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='booked',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='booked',
            field=models.ManyToManyField(to='Jobs.BookJob'),
        ),
    ]
